version: 1
jobs:
  node:
    working_directory: ~/react-native-horizontal-timeline
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-rn
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
